# Generated by Django 3.2.8 on 2022-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProjectApp', '0002_image_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(null=True)),
                ('path', models.CharField(max_length=40)),
            ],
        ),
    ]
